jobs:
- job: 'Win'
  pool: 
    vmImage: 'vs2017-win2016'
  variables:
    CONAN_VISUAL_VERSIONS: 15
    CONAN_BUILD_TYPES: Release
    CONAN_VISUAL_RUNTIMES: MT
  steps:
  - template: .ci/azure-pipelines/build.yml

- job: 'Mac'
  pool: 
    vmImage: 'macOS-10.13'
  variables:
    DEVELOPER_DIR: /Applications/Xcode_10.1.app
    CONAN_APPLE_CLANG_VERSIONS: 10.0
  steps:
  - template: .ci/azure-pipelines/build.yml
